### ISSUE TITLE
Base de datos

### ISSUE THREAD

**Issue by lasagnabruh** [santifiorino/otakuperonista#2]
Por que en vez de poner las imagenes en un simple array no usas una base de datos "real" como mongodb ? Creo que es mucho mas facil, hasta podes hacer un sistema para pushear nuevas imagenes, reducir codigo y hacer mas facil todo.

**Comment by santifiorino** [comment]
Hice un video contando eso mismo. En su momento llegó a tener un tráfico de 2 millones de personas, no le hice backend porque hubiese tenido que pagar un re host. Si me lo pagas vos si hago todo esto que me decis jajaja

**Comment by lasagnabruh** [comment]
Y que host tendrías que usar como para pagar una fortuna ?
